#!/bin/sh

userresources=$HOME/.Xdefaults
# usermodmap=$HOME/.Xmodmap
# sysresources=/usr/X11R6/lib/X11/xinit/.Xresources
# sysmodmap=/usr/X11R6/lib/X11/xinit/.Xmodmap

# merge in defaults and keymaps
test -f $userresources  && xrdb -merge $userresources
# test -f $sysresources   && xrdb -merge $sysresources
# test -f $sysmodmap      && xmodmap $sysmodmap
# test -f $usermodmap     && xmodmap $usermodmap

# nicer cursor
xsetroot.exe -cursor_name left_ptr -fg white -bg black

# open one xterm to start work with :)
# rxvt +sb -e /bin/bash &
xterm &

# wallpaper
/usr/bin/xsri --set /home/taned/files/wallpaper/silence_1920x1200.png &

# spawn x
# exec fvwm-themes-start
exec fvwm2
